### ISSUE TITLE
Add Nano X?

### ISSUE THREAD

**Issue by loganmarchione** [bitcoin-hardware-wallet/bitcoin-hardware-wallet.github.io#2]
Would you consider adding the [Ledger Nano X](https://shop.ledger.com/pages/ledger-nano-x)? Maybe it doesn't deserve an entire column, since it's almost identical to the Nano S, but maybe something like "Ledger [Nano S](https://shop.ledger.com/products/ledger-nano-s)/[Nano X](https://shop.ledger.com/products/ledger-nano-x)" in the same column?

Also, I just listened to you on the Stephan Livera podcast (great episode, btw!) and you mentioned the importance of air-gapped wallets. The [SafePal S1](https://shop.safepal.io/products/safepal-hardware-wallte-s1-bitcoin-wallet) is a new wallet from Binance that is 100% air-gapped, it uses QR codes for everything. Obviously since it's new, it has yet to be really tested, there is a quick review [here](https://www.youtube.com/watch?v=LlUVoqxVAi0). Maybe something to consider in the future...

**Comment by mflaxman** [comment]
Perhaps I haven't researched the Nano X enough, but it's much more expensive and has bluetooth (a big negative for a security product) so it seems strictly inferior. If there was an easy way to communicate that on the website I'm open to it. Perhaps in the FAQ below? I've gotten some questions about older Trezor models as well.

Re SafePal, I don't think it supports multisig? https://docs.safepal.io/security-features?q=multisig

I added a note saying that in https://github.com/bitcoin-hardware-wallet/bitcoin-hardware-wallet.github.io/commit/3827fc85f35ef6242a0a4f8b21e612d01dd66573
